strategy = "polling"

# Poll URL
url = "{{ trmnl.plugin_settings.custom_fields_values.ha_url }}/api/states/{{ trmnl.plugin_settings.custom_fields_values.entity_id }}"

# Plugin metadata
name = "Home Assistant TRMNL"
description = "Displays Home Assistant sensor data in TRMNL"
version = "1.0.0"
author = "@gitstua"
requires_auth_headers = true
update_frequency = "1/min"
data_source = "Home Assistant API"
tags = ["home-assistant", "automation"]

[polling_headers]
Authorization = "Bearer {{ HA_TOKEN }}"
content-type = "application/json"

[custom_fields_values]
ha_url = "http://homeassistant.local:8123"
entity_id = "sensor.example" 