#url = "https://stu-workers.stuey.workers.dev/ndjson-to-json?url=https://ntfy.sh/{trmnl.plugin_settings.custom_fields_values.topic_name}/json?poll=1&since={trmnl.plugin_settings.custom_fields_values.ntfy_since}"

url = "https://stu-workers.stuey.workers.dev/ndjson-to-json?url=https://ntfy.sh/trmnl-example12345/json?poll=1&since=24h"


name = "Ntfy Alerts"
description = "Displays disk alert notifications from ntfy.sh, such as disk full warnings."
version = "1.0.0"
author = "@yourusername"
update_frequency = "every minute"
data_source = "ntfy.sh"
tags = ["alerts", "notifications", "system"] 

# The topic name to subscribe to


# Defined by Form Fields in the plugin settings page, enter values
# Learn how to build form fields here: https://help.usetrmnl.com/en/articles/10513740-custom-plugin-form-builder
[custom_fields_values]
topic_name = "trmnl-example12345"
ntfy_since = "1h"
max_rows = 6