# strategy = "polling" ==> the data will be fetched once, at server start-up
# strategy = "webhook" ==> POST new data to /webhook
strategy = "polling"

# Poll URL (required for polling strategy)
url = "https://ical-to-json.stuey.workers.dev/?url={{ trmnl.plugin_settings.custom_fields_values.calendar_url }}"

# Example google url for testing (add the real value in the .env file)
#url = "https://stucal-92a1.stuey.workers.dev/?timezone=Australia/Sydney&url={{ private_gcal_url }}"

# sample for testing - static content from GitHub repo
#url = "https://stucal-92a1.stuey.workers.dev/?timezone=Australia/Sydney&url=https://raw.githubusercontent.com/gitstua/stu-calendar-wrangler-worker/refs/heads/main/examples/sample.ics&startFrom=2025-02-04&days=1000"

# Plugin metadata
name = "My Agenda"
description = "Shows upcoming events in an agenda view"
version = "1.0.0"
author = "@gitstua"
requires_auth_headers = false
update_frequency = "5/min"
data_source = "iCal to JSON API"
tags = ["calendar", "agenda", "events"]

# Polling headers (optional, for polling strategy)
[polling_headers]
X-API-Key = "{{ X_API_Key }}"
content-type = "application/json"

[custom_fields_values]
calendar_url = "https://calendar.google.com/calendar/ical/example%40gmail.com/public/basic.ics"