# strategy = "polling" ==> the data will be fetched once, at server start-up
# strategy = "webhook" ==> POST new data to /webhook
strategy = "polling"

# Poll URL (required for polling strategy)
url = "https://api.currencyapi.com/v3/latest?currencies=AUD%2CUSD"

# Plugin metadata
name = "Currency Exchange Rates"
description = "Display current exchange rates for AUD and USD"
version = "1.0.0"
author = "@gitstua"
requires_auth_headers = true
update_frequency = "1/day"
data_source = "https://app.currencyapi.com/ JSON"
tags = ["finance"]

# Polling headers (optional, for polling strategy)
[polling_headers]
authorization = "bearer 123"
content-type = "application/json" 