strategy = "webhook"

# Poll URL (required for polling strategy)
# url = "https://official-joke-api.appspot.com/random_joke"

# Plugin metadata
name = "Home Assistant TRMNL"
description = "Monitor and control your Home Assistant devices directly from TRMNL. View device states, sensor readings, and automation status."
version = "1.0.0"
author = "@gitstua"
update_frequency = "30s"
data_source = "Home Assistant API"
tags = ["smart home", "automation", "monitoring"] 