# strategy = "polling" ==> the data will be fetched once, at server start-up
# strategy = "webhook" ==> POST new data to /webhook
strategy = "polling"

# Poll URL (required for polling strategy)
url = "https://raw.githubusercontent.com/openfootball/football.json/refs/heads/master/2024-25/en.1.json"

# Plugin metadata
name = "EPL My Team"
description = "Displays Manchester United's fixtures and results from the open football.json dataset. Shows past results and upcoming matches for the current season."
version = "1.0.0"
author = "@gitstua"
update_frequency = "2/day"
data_source = "OpenFootball JSON"
tags = ["sports", "football", "premier-league", "manchester-united"] 