---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://raw.githubusercontent.com/openfootball/football.json/refs/heads/master/2024-25/en.1.json
polling_headers: 'content-type: application/json'
name: EPL Fixtures
description: Shows English Premier League fixtures and results from the open football.json dataset. Displays match dates, teams, and scores for the current season.
refresh_interval: 43200