# strategy = "polling" ==> the data will be fetched once, at server start-up
# strategy = "webhook" ==> POST new data to /webhook
strategy = "polling"

# Poll URL (required for polling strategy)
url = "https://example.com/api/movies"

# Plugin metadata
name = "Jellyfin Sample for RG"
description = "Displays a list of unwatched movies sorted by rating."
version = "1.0.0"
author = "@yourusername"
update_frequency = "hourly"
data_source = "Jellyfin API"
tags = ["entertainment", "movies"] 