

name: Fly Deploy
on:
  push:
    branches:
      - main    # change to main if needed
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.toml -a trmnl-plugins
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: echo "url=https://trmnl-plugins.fly.dev/" >> $GITHUB_OUTPUT
  
