name: Build and Push Docker Image

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get Version
        id: package-version
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            stegg/${{ github.event.repository.name }}:${{ env.VERSION }}
            stegg/${{ github.event.repository.name }}:latest
          platforms: linux/amd64,linux/arm64