# fly.toml app configuration file generated for trmnl-plugins on 2025-02-07T19:30:41+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trmnl-plugins'
primary_region = 'syd'


[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source="trmnl_cache"
  destination="/data/cache"
